// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

package messages

//go:generate minimock -i github.com/Svoevolin/workshop_1_bot/internal/model/messages.ExchangeRateUpdate -o exchange_rate_update_mock.go -n ExchangeRateUpdateMock -p messages

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	"time"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ExchangeRateUpdateMock implements messages.ExchangeRateUpdate
type ExchangeRateUpdateMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcUpdateCurrency          func(ctx context.Context, time time.Time) (err error)
	inspectFuncUpdateCurrency   func(ctx context.Context, time time.Time)
	afterUpdateCurrencyCounter  uint64
	beforeUpdateCurrencyCounter uint64
	UpdateCurrencyMock          mExchangeRateUpdateMockUpdateCurrency
}

// NewExchangeRateUpdateMock returns a mock for messages.ExchangeRateUpdate
func NewExchangeRateUpdateMock(t minimock.Tester) *ExchangeRateUpdateMock {
	m := &ExchangeRateUpdateMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.UpdateCurrencyMock = mExchangeRateUpdateMockUpdateCurrency{mock: m}
	m.UpdateCurrencyMock.callArgs = []*ExchangeRateUpdateMockUpdateCurrencyParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mExchangeRateUpdateMockUpdateCurrency struct {
	mock               *ExchangeRateUpdateMock
	defaultExpectation *ExchangeRateUpdateMockUpdateCurrencyExpectation
	expectations       []*ExchangeRateUpdateMockUpdateCurrencyExpectation

	callArgs []*ExchangeRateUpdateMockUpdateCurrencyParams
	mutex    sync.RWMutex
}

// ExchangeRateUpdateMockUpdateCurrencyExpectation specifies expectation struct of the ExchangeRateUpdate.UpdateCurrency
type ExchangeRateUpdateMockUpdateCurrencyExpectation struct {
	mock    *ExchangeRateUpdateMock
	params  *ExchangeRateUpdateMockUpdateCurrencyParams
	results *ExchangeRateUpdateMockUpdateCurrencyResults
	Counter uint64
}

// ExchangeRateUpdateMockUpdateCurrencyParams contains parameters of the ExchangeRateUpdate.UpdateCurrency
type ExchangeRateUpdateMockUpdateCurrencyParams struct {
	ctx  context.Context
	time time.Time
}

// ExchangeRateUpdateMockUpdateCurrencyResults contains results of the ExchangeRateUpdate.UpdateCurrency
type ExchangeRateUpdateMockUpdateCurrencyResults struct {
	err error
}

// Expect sets up expected params for ExchangeRateUpdate.UpdateCurrency
func (mmUpdateCurrency *mExchangeRateUpdateMockUpdateCurrency) Expect(ctx context.Context, time time.Time) *mExchangeRateUpdateMockUpdateCurrency {
	if mmUpdateCurrency.mock.funcUpdateCurrency != nil {
		mmUpdateCurrency.mock.t.Fatalf("ExchangeRateUpdateMock.UpdateCurrency mock is already set by Set")
	}

	if mmUpdateCurrency.defaultExpectation == nil {
		mmUpdateCurrency.defaultExpectation = &ExchangeRateUpdateMockUpdateCurrencyExpectation{}
	}

	mmUpdateCurrency.defaultExpectation.params = &ExchangeRateUpdateMockUpdateCurrencyParams{ctx, time}
	for _, e := range mmUpdateCurrency.expectations {
		if minimock.Equal(e.params, mmUpdateCurrency.defaultExpectation.params) {
			mmUpdateCurrency.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateCurrency.defaultExpectation.params)
		}
	}

	return mmUpdateCurrency
}

// Inspect accepts an inspector function that has same arguments as the ExchangeRateUpdate.UpdateCurrency
func (mmUpdateCurrency *mExchangeRateUpdateMockUpdateCurrency) Inspect(f func(ctx context.Context, time time.Time)) *mExchangeRateUpdateMockUpdateCurrency {
	if mmUpdateCurrency.mock.inspectFuncUpdateCurrency != nil {
		mmUpdateCurrency.mock.t.Fatalf("Inspect function is already set for ExchangeRateUpdateMock.UpdateCurrency")
	}

	mmUpdateCurrency.mock.inspectFuncUpdateCurrency = f

	return mmUpdateCurrency
}

// Return sets up results that will be returned by ExchangeRateUpdate.UpdateCurrency
func (mmUpdateCurrency *mExchangeRateUpdateMockUpdateCurrency) Return(err error) *ExchangeRateUpdateMock {
	if mmUpdateCurrency.mock.funcUpdateCurrency != nil {
		mmUpdateCurrency.mock.t.Fatalf("ExchangeRateUpdateMock.UpdateCurrency mock is already set by Set")
	}

	if mmUpdateCurrency.defaultExpectation == nil {
		mmUpdateCurrency.defaultExpectation = &ExchangeRateUpdateMockUpdateCurrencyExpectation{mock: mmUpdateCurrency.mock}
	}
	mmUpdateCurrency.defaultExpectation.results = &ExchangeRateUpdateMockUpdateCurrencyResults{err}
	return mmUpdateCurrency.mock
}

// Set uses given function f to mock the ExchangeRateUpdate.UpdateCurrency method
func (mmUpdateCurrency *mExchangeRateUpdateMockUpdateCurrency) Set(f func(ctx context.Context, time time.Time) (err error)) *ExchangeRateUpdateMock {
	if mmUpdateCurrency.defaultExpectation != nil {
		mmUpdateCurrency.mock.t.Fatalf("Default expectation is already set for the ExchangeRateUpdate.UpdateCurrency method")
	}

	if len(mmUpdateCurrency.expectations) > 0 {
		mmUpdateCurrency.mock.t.Fatalf("Some expectations are already set for the ExchangeRateUpdate.UpdateCurrency method")
	}

	mmUpdateCurrency.mock.funcUpdateCurrency = f
	return mmUpdateCurrency.mock
}

// When sets expectation for the ExchangeRateUpdate.UpdateCurrency which will trigger the result defined by the following
// Then helper
func (mmUpdateCurrency *mExchangeRateUpdateMockUpdateCurrency) When(ctx context.Context, time time.Time) *ExchangeRateUpdateMockUpdateCurrencyExpectation {
	if mmUpdateCurrency.mock.funcUpdateCurrency != nil {
		mmUpdateCurrency.mock.t.Fatalf("ExchangeRateUpdateMock.UpdateCurrency mock is already set by Set")
	}

	expectation := &ExchangeRateUpdateMockUpdateCurrencyExpectation{
		mock:   mmUpdateCurrency.mock,
		params: &ExchangeRateUpdateMockUpdateCurrencyParams{ctx, time},
	}
	mmUpdateCurrency.expectations = append(mmUpdateCurrency.expectations, expectation)
	return expectation
}

// Then sets up ExchangeRateUpdate.UpdateCurrency return parameters for the expectation previously defined by the When method
func (e *ExchangeRateUpdateMockUpdateCurrencyExpectation) Then(err error) *ExchangeRateUpdateMock {
	e.results = &ExchangeRateUpdateMockUpdateCurrencyResults{err}
	return e.mock
}

// UpdateCurrency implements messages.ExchangeRateUpdate
func (mmUpdateCurrency *ExchangeRateUpdateMock) UpdateCurrency(ctx context.Context, time time.Time) (err error) {
	mm_atomic.AddUint64(&mmUpdateCurrency.beforeUpdateCurrencyCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateCurrency.afterUpdateCurrencyCounter, 1)

	if mmUpdateCurrency.inspectFuncUpdateCurrency != nil {
		mmUpdateCurrency.inspectFuncUpdateCurrency(ctx, time)
	}

	mm_params := ExchangeRateUpdateMockUpdateCurrencyParams{ctx, time}

	// Record call args
	mmUpdateCurrency.UpdateCurrencyMock.mutex.Lock()
	mmUpdateCurrency.UpdateCurrencyMock.callArgs = append(mmUpdateCurrency.UpdateCurrencyMock.callArgs, &mm_params)
	mmUpdateCurrency.UpdateCurrencyMock.mutex.Unlock()

	for _, e := range mmUpdateCurrency.UpdateCurrencyMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpdateCurrency.UpdateCurrencyMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateCurrency.UpdateCurrencyMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateCurrency.UpdateCurrencyMock.defaultExpectation.params
		mm_got := ExchangeRateUpdateMockUpdateCurrencyParams{ctx, time}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateCurrency.t.Errorf("ExchangeRateUpdateMock.UpdateCurrency got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateCurrency.UpdateCurrencyMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateCurrency.t.Fatal("No results are set for the ExchangeRateUpdateMock.UpdateCurrency")
		}
		return (*mm_results).err
	}
	if mmUpdateCurrency.funcUpdateCurrency != nil {
		return mmUpdateCurrency.funcUpdateCurrency(ctx, time)
	}
	mmUpdateCurrency.t.Fatalf("Unexpected call to ExchangeRateUpdateMock.UpdateCurrency. %v %v", ctx, time)
	return
}

// UpdateCurrencyAfterCounter returns a count of finished ExchangeRateUpdateMock.UpdateCurrency invocations
func (mmUpdateCurrency *ExchangeRateUpdateMock) UpdateCurrencyAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateCurrency.afterUpdateCurrencyCounter)
}

// UpdateCurrencyBeforeCounter returns a count of ExchangeRateUpdateMock.UpdateCurrency invocations
func (mmUpdateCurrency *ExchangeRateUpdateMock) UpdateCurrencyBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateCurrency.beforeUpdateCurrencyCounter)
}

// Calls returns a list of arguments used in each call to ExchangeRateUpdateMock.UpdateCurrency.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateCurrency *mExchangeRateUpdateMockUpdateCurrency) Calls() []*ExchangeRateUpdateMockUpdateCurrencyParams {
	mmUpdateCurrency.mutex.RLock()

	argCopy := make([]*ExchangeRateUpdateMockUpdateCurrencyParams, len(mmUpdateCurrency.callArgs))
	copy(argCopy, mmUpdateCurrency.callArgs)

	mmUpdateCurrency.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateCurrencyDone returns true if the count of the UpdateCurrency invocations corresponds
// the number of defined expectations
func (m *ExchangeRateUpdateMock) MinimockUpdateCurrencyDone() bool {
	for _, e := range m.UpdateCurrencyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateCurrencyMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterUpdateCurrencyCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateCurrency != nil && mm_atomic.LoadUint64(&m.afterUpdateCurrencyCounter) < 1 {
		return false
	}
	return true
}

// MinimockUpdateCurrencyInspect logs each unmet expectation
func (m *ExchangeRateUpdateMock) MinimockUpdateCurrencyInspect() {
	for _, e := range m.UpdateCurrencyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ExchangeRateUpdateMock.UpdateCurrency with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateCurrencyMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterUpdateCurrencyCounter) < 1 {
		if m.UpdateCurrencyMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ExchangeRateUpdateMock.UpdateCurrency")
		} else {
			m.t.Errorf("Expected call to ExchangeRateUpdateMock.UpdateCurrency with params: %#v", *m.UpdateCurrencyMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateCurrency != nil && mm_atomic.LoadUint64(&m.afterUpdateCurrencyCounter) < 1 {
		m.t.Error("Expected call to ExchangeRateUpdateMock.UpdateCurrency")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ExchangeRateUpdateMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockUpdateCurrencyInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ExchangeRateUpdateMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ExchangeRateUpdateMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockUpdateCurrencyDone()
}
